DOMAIN = "ff_le_03mw"

CONF_HOST = "host"
CONF_PORT = "port"
CONF_SLAVE_ID = "slave"
CONF_SCAN_INTERVAL = "scan_interval"

DEFAULT_HOST = "192.168.86.199"
DEFAULT_PORT = 4196
DEFAULT_SLAVE_ID = 5
DEFAULT_SCAN_INTERVAL = 10